### ISSUE TITLE
Upgrade requirements-detector / remove pylint-plugin-utils as a direct dependency

### ISSUE THREAD

**Issue by carlio** [prospector-dev/prospector#676]
Based on [this conversation](https://github.com/prospector-dev/prospector/issues/670#issuecomment-2397340662), it seems like `pylint-plugin-utils` could be removed as a direct dependency from `pyproject.toml`

Also, in #640 - see [this comment](https://github.com/prospector-dev/prospector/issues/670#issuecomment-2393350433) - the only compatible version of `requirements-detector` with pylint 3 and the current astroid version will be `>=1.3.1` so this should also be updated in `pyproject.toml`. The current version constraints will pull that on a fresh build, however old virtualenvs won't feel the need to update it when updating prospector, this could lead to issues.

(Maybe at the same time, running `poetry update` to get latest versions of other dependencies in the `poetry.lock` file is a good idea)

**Comment by carlio** [comment]
I'll add that perhaps pylint-celery and maybe pylint-flask would need updates too but I'm not sure

**Comment by valeriupredoi** [comment]
Hi @carlio @Pierre-Sassoulas - ah a very good call about this issue, was just about to drop one myself! So, from your friendly conda feedstock guy (me :grinning: ), the current table of dependencies for v1.12.0 [looks like this](https://github.com/conda-forge/prospector-feedstock/blob/main/recipe/meta.yaml) - there are a few issues that we should fix at upstream and methinks rebuild a build 1 soon:

- this one about `pylint-plugin-utils` - this needs be removed or unpinned in the PyPI package so...
- ...we can readd `pip check` as a safety net; the check currently fails due to the upper bound pin on `pylint-plugin-utils` that restricts pylint-django` that in turn restricts `pylint>=3` (don't we all love dependency tables? :laughing: )
- `flake8` is currently pinned upper bound `<7` and that is causing a few headaches alsewhere, mostly in heavy/large environments that mamba tries to solve with the latest versions for packages; also `flake8` is free at lower bound - do you guys need a hard `>=6` pin?

I can get a build=1 out asap as soon as I know what to do, and when a new PyPI build is out.

Cheers :beer:
